### ISSUE TITLE
How to append screenshots to xml report ?

### ISSUE THREAD

**Issue by bheemreddy181** [spekt/nunit.testlogger#96] opened 2022-11-29 16:42 UTC
Hey Team,

Is there a way for failed tests, we can append the screenshot paths to the report so that any reporting dashboards can pick them up ?

Regards
Bheem

**Comment by Siphonophora** [comment] 2022-11-30 01:21
Hi @bheemreddy181 as you saw, this is a duplicate of #54

**Comment by bheemreddy181** [comment] 2022-11-30 01:37
Cool sounds good. Can we update this with latest dotnet packages ?

**Comment by Siphonophora** [comment] 2022-11-30 04:23
Are you seeing a compatibility issue? This should work with .net 7

**Comment by codito** [comment] 2023-07-05 06:21
Duplicate of #54

**Closed by codito** 2023-07-05 06:21 UTC
